export default [
  'Canada',
  'Japan',
  'Norway',
  'Wales',
  'United States of America',
  'Denmark',
  'Switzerland',
  'Turkey',
  'Portugal',
  'Netherlands',
  'Uruguay',
  'Egypt',
  'Mexico',
  'Kenya',
  'Ethiopia',
  'Ghana',
  'United Kingdom',
  'People\'s Republic of China',
  'Latvia',
  'Czech Republic',
  'Slovakia',
  'Romania',
  'Bulgaria',
  'Croatia',
  'Kazakhstan',
  'Montenegro',
  'Barbados',
  'Indonesia',
  'South Africa',
  'Algeria',
  'Uzbekistan',
  'Chile',
  'Singapore',
  'Bahrain',
  'Australia',
  'Argentina',
  'Peru',
  'North Korea',
  'Cambodia',
  'East Timor',
  'Chad',
  'New Zealand',
  'India',
  'Tuvalu',
  'Samoa',
  'Solomon Islands',
  'Vanuatu',
  'Papua New Guinea',
  'Palau',
  'Nauru',
  'Federated States of Micronesia',
  'Marshall Islands',
  'Kiribati',
  'Mongolia',
  'Fiji',
  'Venezuela',
  'Paraguay',
  'Guyana',
  'Ecuador',
  'Colombia',
  'Bolivia',
  'Trinidad and Tobago',
  'Saint Vincent and the Grenadines',
  'Saint Lucia',
  'Saint Kitts and Nevis',
  'Jamaica',
  'Grenada',
  'Guatemala',
  'Bahamas',
  'Antigua and Barbuda',
  'Honduras',
  'Dominica',
  'Dominican Republic',
  'Haiti',
  'El Salvador',
  'Iran',
  'Iraq',
  'Costa Rica',
  'Israel',
  'Yemen',
  'Jordan',
  'Nicaragua',
  'Kyrgyzstan',
  'Laos',
  'Lebanon',
  'Maldives',
  'Malaysia',
  'Myanmar',
  'Nepal',
  'Oman',
  'Pakistan',
  'Qatar',
  'Saudi Arabia',
  'Sri Lanka',
  'Syria',
  'Tajikistan',
  'Taiwan',
  'Thailand',
  'Turkmenistan',
  'United Arab Emirates',
  'Vietnam',
  'South Korea',
  'Afghanistan',
  'Bangladesh',
  'Mali',
  'Angola',
  'Bhutan',
  'Brunei',
  'Tanzania',
  'Philippines',
  'Central African Republic',
  'Togo',
  'Tunisia',
  'Zambia',
  'Zimbabwe',
  'South Sudan',
  'Benin',
  'Botswana',
  'Burundi',
  'Comoros',
  'Republic of the Congo',
  'Democratic Republic of the Congo',
  'Djibouti',
  'Eritrea',
  'Gabon',
  'Gambia',
  'Guinea',
  'Guinea-Bissau',
  'Ivory Coast',
  'Cameroon',
  'Cape Verde',
  'Lesotho',
  'Liberia',
  'Libya',
  'Madagascar',
  'Malawi',
  'Mauritania',
  'Mauritius',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Niger',
  'Nigeria',
  'Uganda',
  'Rwanda',
  'São Tomé and Príncipe',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'Somalia',
  'Sudan',
  'Eswatini',
  'Northern Mariana Islands',
  'Cook Islands',
  'Kingdom of the Netherlands',
  'Niue',
  'Sahrawi Arab Democratic Republic',
  'Kingdom of Aksum',
  'State of Syria',
  'State of Palestine',
  'Kush',
  'Artsakh',
  'Alodia',
  'Giudicato of Cagliari',
  'Dál nAraidi',
];
